[package]
name = "sequoia-ffi"
version = "0.1.0"
authors = ["Justus Winter <justus@pep-project.org>"]

[dependencies]
openpgp = { path = "../openpgp" }
sequoia-core = { path = "../core" }
sequoia-store = { path = "../store" }
sequoia-net = { path = "../net" }
failure = "0.1.2"
lazy_static = "1.0.0"
libc = "0.2.33"
native-tls = "0.2.0"

[dev-dependencies]
nettle = { git = "https://gitlab.com/sequoia-pgp/nettle-rs.git" }

[lib]
crate-type = ["cdylib", "staticlib"]
