[package]
name = "openpgp"
version = "0.1.0"
authors = ["Neal H. Walfield <neal@gnu.org>"]

[dependencies]
buffered-reader = { path = "../buffered-reader" }
base64 = "0.9.0"
bzip2 = "0.3.2"
failure = "0.1.1"
flate2 = "1.0.1"
nettle = { git = "https://gitlab.com/sequoia-pgp/nettle-rs.git" }
quickcheck = "0.6"
time = "0.1.38"
