[package]
name = "openpgp"
version = "0.1.0"
authors = ["Neal H. Walfield <neal@gnu.org>"]

[dependencies]
buffered-reader = { path = "../buffered-reader" }
base64 = "0.8.0"
nom = "3.2.0"
num = "0.1.40"
num-derive = "0.1.41"
