[package]
name = "openpgp"
version = "0.1.0"
authors = ["Neal H. Walfield <neal@gnu.org>"]

[dependencies]
buffered-reader = { path = "../buffered-reader" }
base64 = "0.8.0"
bzip2 = "0.3.2"
flate2 = "0.2"
nettle = { git = "https://gitlab.com/sequoia-pgp/nettle-rs.git" }
num = "0.1.40"
num-derive = "0.1.41"
