image: registry.gitlab.com/sequoia-pgp/build-docker-image:latest

test:
  script:
    - if [ -d target ]; then find target | wc --lines; du -sh target; fi
    - if [ -d cargo ]; then find cargo | wc --lines; du -sh cargo; fi
    - rustc --version
    - cargo --version
    - clang --version
    - SEQUOIA_CTEST_VALGRIND=/usr/bin/valgrind make test
    - cargo clean -p buffered-reader -p sequoia-rfc2822 -p sequoia-openpgp -p sequoia-openpgp-ffi -p sequoia-core -p sequoia-ffi -p sequoia-ffi-macros -p sequoia-ipc -p sequoia-net -p sequoia-store -p sequoia-tool -p sequoia-sqv -p sequoia-guide
    - du -sh target
    - du -sh cargo

cache:
  paths:
    - target/
    - cargo/

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  CARGO_FLAGS: --color always
  CARGO_INCREMENTAL: 0
