[package]
name = "sequoia"
version = "0.1.0"
authors = ["Neal H. Walfield <neal@gnu.org>"]

[dependencies]
libc = "0.2.33"
nom = "3.2.0"
num = "0.1.40"
num-derive = "0.1.41"
flate2 = "0.2"
bzip2 = "0.3.2"

[lib]
name = "sequoia"
path = "src/lib.rs"
crate-type = ["lib", "dylib"]

[[bin]]
doc = false
name = "sequoia"
path = "src/sequoia.rs"
