[package]
name = "sequoia"
version = "0.1.0"
authors = ["Neal H. Walfield <neal@gnu.org>"]

[dependencies]
base64 = "0.8.0"
bzip2 = "0.3.2"
flate2 = "0.2"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.2"
libc = "0.2.33"
native-tls = "0.1.4"
nom = "3.2.0"
num = "0.1.40"
num-derive = "0.1.41"
percent-encoding = "1.0.1"
tokio-core = "0.1"

[lib]
name = "sequoia"
path = "src/lib.rs"
crate-type = ["lib", "dylib"]

[[bin]]
doc = false
name = "sequoia"
path = "src/sequoia.rs"
