[package]
name = "sequoia"
version = "0.1.0"
authors = ["Neal H. Walfield <neal@gnu.org>"]
documentation = "https://docs.sequoia-pgp.org/"
homepage = "https://sequoia-pgp.org/"
repository = "https://gitlab.com/sequoia-pgp/sequoia"
readme = "README.md"
publish = false # not yet...


[workspace]

[dependencies]
buffered-reader = { path = "buffered-reader" }
openpgp = { path = "openpgp" }
sequoia-core = { path = "core" }
sequoia-ffi = { path = "ffi" }
sequoia-net = { path = "net" }
sequoia-store = { path = "store" }
sequoia-tool = { path = "tool" }

[lib]
name = "sequoia"
path = "src/lib.rs"
