[package]
name = "sequoia-tool"
version = "0.1.0"
authors = ["Justus Winter <justus@pep-project.org>"]
build = "build.rs"

[dependencies]
openpgp = { path = "../openpgp" }
sequoia-core = { path = "../core" }
sequoia-net = { path = "../net" }
sequoia-store = { path = "../store" }
clap = "2.27.1"
failure = "0.1.1"
prettytable-rs = "0.6.7"
rpassword = "2.0.0"
time = "0.1.38"

[build-dependencies]
clap = "2.27.1"

[[bin]]
name = "sq"
path = "src/usage.rs"
