[package]
name = "sequoia-net"
version = "0.1.0"
authors = ["Justus Winter <justus@pep-project.org>"]

[dependencies]
openpgp = { path = "../openpgp" }
sequoia-core = { path = "../core" }
hyper = "0.11"
hyper-tls = "0.1.2"
libc = "0.2.33"
native-tls = "0.1.4"
nom = "3.2.0"
num = "0.1.40"
num-derive = "0.1.41"
percent-encoding = "1.0.1"
tokio-core = "0.1"
futures = "0.1"
